services:
  - type: web
    name: ratel-signals-telegram-bot
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
      - key: WEBHOOK_URL
      - key: FRONTEND_ORIGIN
