export default function AlertsPage() {
  return (
    <main className="min-h-screen bg-[#05060A] px-6 py-8 text-white md:px-12">
      <div className="mx-auto max-w-6xl rounded-[32px] border border-white/10 bg-slate-950/80 p-8 shadow-glow backdrop-blur-xl">
        <h1 className="text-3xl font-semibold">AI Alerts</h1>
        <p className="mt-3 text-slate-400">View the latest bullish, bearish, and arbitrage insight cards generated by our intelligence engine.</p>
        <div className="mt-8 grid gap-6">
          {['Funding arbitrage', 'Squeeze setup', 'Whale accumulation', 'Cross-exchange anomaly'].map((option) => (
            <div key={option} className="rounded-3xl border border-white/10 bg-slate-900/90 p-6">
              <p className="text-sm uppercase tracking-[0.3em] text-fuchsia-300">Signal</p>
              <h2 className="mt-3 text-xl font-semibold text-white">{option}</h2>
              <p className="mt-2 text-slate-300">AI-driven analysis to help you monitor risk and spot the next major funding move.</p>
            </div>
          ))}
        </div>
      </div>
    </main>
  );
}
